---
- hosts: k8s_master:k8s_nodes
  tasks:
      - name: Performing a Package Upgrade.
        become: yes
        yum:
            name: '*'
            state: latest

      - name: Adding the Docker-ce repository.
        become: yes
        shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

      - name: Adding the Kubernetes repository.
        become: yes
        yum_repository:
            name: Kubernetes
            description: "Kubernetes repository to install kubeadm"
            baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
            gpgcheck: yes
            repo_gpgcheck: yes
            gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

      - name: Installing the epel repository.
        become: yes
        yum:
            name: epel-release

      - name: Installing the base packages.
        become: yes
        yum:
            name: ['openssl', 'vim', 'wget', 'tree', 'curl', 'mlocate', 'nmap', 'net-tools', 'bind-utils', 'lsof', 'htop', 'iotop', 'bmon', 'sysstat']

      - name: Installing the required packages to bootstrap a kubernetes cluster.
        become: yes
        yum:
            name: ['docker-ce', 'kubelet', 'kubeadm', 'kubectl']

      - name: Creating the initial database for mlocate.
        become: yes
        shell: updatedb

      - name: Enabling the systemd module for docker-ce.
        become: yes
        systemd: 
            state: started
            name: docker
            enabled: yes

      - name: Enabling the systemd module for the kubelet.
        become: yes
        systemd:
            state: started
            name: kubelet
            enabled: yes